<?php
/*@var $cart Mage_Sales_Model_Quote */
$cart = $this->getCart();
?>

<table width="680" border="0" align="left" cellpadding="0" cellspacing="0">
    <tbody>
<?php foreach ($cart->getAllVisibleItems() as $item): ?>
    <?php $itemLink = Mage::helper('abandonment')->getItemLink($cart, $cart->getReminderTemplate(), $item->getProductId());?>
        <tr>
            <td align="center">
            <table width="680"
                style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; line-height: 16px; color: #000000"
                border="1" align="center" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td width="385" height="25">
                        <table width="385" border="0" cellspacing="0" cellpadding="0">
                            <tbody>
                                <tr>
                                    <td width="85">
                                        <a
                                        href="<?php echo $itemLink?>"
                                        title="Checkout Now" target="_blank">
                                        <img
                                            alt="<?php echo $this->escapeHtml($item->getName()) ?>"
                                            border="0" style="display: block;"
                                            src="<?php echo Mage::helper('abandonment')->getProductImageUrl($item) ?>"
                                            width="85" />
                                        </a>
                                    </td>
                                    <td width="8">&nbsp;</td>
                                    <td><a
                                        href="<?php echo $itemLink ?>"
                                        title="<?php echo $this->escapeHtml($item->getName()) ?>"><font
                                        color="#000000"> <strong><?php echo $this->escapeHtml($item->getName()) ?></strong>
                                    </font>
                                    </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        </td>
                        <td width="80" height="25" align="center"><?php echo Mage::helper('checkout')->formatPrice($item->getBasePrice(), true, true) ?></td>
                        <td width="59" height="25" align="center"><?php echo floor($item->getQty()) ?></td>
                        <td width="80" height="25" align="center"><?php echo Mage::helper('checkout')->formatPrice($item->getBaseRowTotal(), true, true)?></td>
                    </tr>
                </tbody>
            </table>
            </td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>