<?php
/**
 * @category   Auguria
 * @package    Auguria_EmailVision
 * @author     Auguria
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License version 3 (GPLv3)
 *
 * EmailVision getFields button to call the concerned controller action
 */
?>
<a href="<?php echo Mage::getSingleton('adminhtml/url')->getUrl('emv_datasync/dataSync/getMemberFields');?>">
    <button class="scalable" type="button">
        <span id="validation_result"><?php echo $this->__('Get SmartFocus member fields') ?></span>
    </button>
</a>
